version: '1.0'

services:
  postgres:
    container_name: nestjs-course-http-module
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data    
    networks:
      - nestjs-course-http-module

volumes:
  postgres_data:

networks:
  nestjs-course-http-module:  